CREATE DATABASE MENIN_BD
GO
USE MENIN_BD
GO

CREATE TABLE CLIENTES (
	CLI_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CLI_NOME VARCHAR(45) NOT NULL,
	CLI_SOBRENOME VARCHAR(45) NOT NULL,
	CLI_CPF VARCHAR(13) NOT NULL UNIQUE,
	CLI_CELULAR VARCHAR(13) NOT NULL,
	CLI_TELEFONE VARCHAR(13)
);
GO
CREATE TABLE PRODUTOS (
	PROD_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PROD_NOME VARCHAR(45) NOT NULL,
	PROD_PRECO DECIMAL(10, 3) NOT NULL
);
GO
CREATE TABLE DESCONTOS (
	DESC_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DESC_DATA_INICIAL DATETIME NOT NULL,
	DESC_DATA_FINAL DATETIME NOT NULL,
	DESC_ID_PROD INTEGER NOT NULL,
	DESC_PERCENTUAL INTEGER DEFAULT 0 NOT NULL,
	DESC_DATA_CRIACAO DATETIME DEFAULT GETDATE() NOT NULL, 
	DESC_SITUACAO AS (CASE WHEN (DESC_DATA_CRIACAO >= DESC_DATA_INICIAL AND DESC_DATA_CRIACAO <= DESC_DATA_FINAL) THEN 'A' ELSE 'I' END) PERSISTED
);
GO
ALTER TABLE DESCONTOS ADD CONSTRAINT FK_DESC_REF_PRODUTO FOREIGN KEY (DESC_ID_PROD) REFERENCES PRODUTOS(PROD_ID);
GO
CREATE TABLE COMPRAS (
	COM_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COM_ID_CLIENTE INTEGER NOT NULL,
	COM_DATA TIMESTAMP NOT NULL,
	COM_PRECO_TOTAL DECIMAL(10,3) DEFAULT 0 NOT NULL
);
GO
ALTER TABLE COMPRAS ADD CONSTRAINT FK_COMP_REF_CLIENTE FOREIGN KEY (COM_ID_CLIENTE) REFERENCES CLIENTES(CLI_ID);
GO
CREATE TABLE ITENS_COMPRA (
	ITEC_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ITEC_ID_COMPRA INTEGER NOT NULL,
	ITEC_ID_PRODUTO INTEGER NOT NULL,
	ITEC_QNTD INTEGER NOT NULL,
	ITEC_ID_DESCONTO INTEGER
);
GO
ALTER TABLE ITENS_COMPRA ADD CONSTRAINT FK_ITEM_REF_COMPRA FOREIGN KEY (ITEC_ID_COMPRA) REFERENCES COMPRAS(COM_ID);
GO
ALTER TABLE ITENS_COMPRA ADD CONSTRAINT FK_ITEM_REF_PRODUTO FOREIGN KEY (ITEC_ID_PRODUTO) REFERENCES PRODUTOS(PROD_ID);
GO
ALTER TABLE ITENS_COMPRA ADD CONSTRAINT FK_ITEM_REF_DESCONTO FOREIGN KEY (ITEC_ID_DESCONTO) REFERENCES DESCONTOS(DESC_ID);
GO
CREATE OR ALTER TRIGGER TG_COMPRA_PRECO_TOTAL
ON ITENS_COMPRA
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    UPDATE COMPRAS SET COM_PRECO_TOTAL = (
    SELECT COALESCE(SUM(IC.ITEC_QNTD * P.PROD_PRECO) - (SUM((IC.ITEC_QNTD * P.PROD_PRECO) * COALESCE(DESC_PERCENTUAL, 0) / 100)),0)
    FROM COMPRAS C 
    INNER JOIN ITENS_COMPRA IC ON IC.ITEC_ID_COMPRA = C.COM_ID
    LEFT JOIN PRODUTOS P ON P.PROD_ID = IC.ITEC_ID_PRODUTO
    LEFT JOIN DESCONTOS ON DESC_ID = ITEC_ID_DESCONTO AND DESC_ID_PROD = ITEC_ID_PRODUTO AND DESC_SITUACAO = 'A'
    WHERE C.COM_ID = COM_ID) WHERE EXISTS (SELECT 1 FROM inserted WHERE inserted.ITEC_ID_COMPRA = COM_ID) OR EXISTS (SELECT 1 FROM deleted WHERE deleted.ITEC_ID_COMPRA = COM_ID)
END
GO

/*CREATE OR ALTER PROCEDURE ALTERAR_CLIENTES (@CLI_ID INTEGER,  @CLI_NOME VARCHAR(45), @CLI_SOBRENOME VARCHAR(45), @CLI_CPF VARCHAR(13), @CLI_CELULAR VARCHAR(13), @CLI_TELEFONE VARCHAR(13))
AS
	IF (@CLI_ID IS NULL)
	BEGIN
		INSERT INTO CLIENTES (CLI_NOME, @CLI_SOBRENOME, CLI_CPF, CLI_IDADE, CLI_CIDADE) VALUES (@CLI_NOME, @CLI_CPF, @CLI_IDADE, @CLI_CIDADE);
	END
	ELSE
	BEGIN
		PRINT('Não é possível cadastrar o cliente');
	END
GO*/

-- Inserção na tabela CLIENTES
INSERT INTO CLIENTES (CLI_NOME, CLI_SOBRENOME, CLI_CPF, CLI_CELULAR, CLI_TELEFONE)
VALUES ('João', 'Silva', '12345678901', '999999999', '888888888');

-- Inserção na tabela PRODUTOS
INSERT INTO PRODUTOS (PROD_NOME, PROD_PRECO)
VALUES ('Camiseta', 29.99),
       ('Calça', 59.99),
       ('Tênis', 99.99);

-- Inserção na tabela DESCONTOS
-- Inserção na tabela DESCONTOS
INSERT INTO DESCONTOS (DESC_DATA_INICIAL, DESC_DATA_FINAL, DESC_ID_PROD, DESC_PERCENTUAL, DESC_DATA_CRIACAO)
VALUES (CONVERT(DATETIME, '2023-06-01', 120), CONVERT(DATETIME, '2023-06-30', 120), 1, 10, GETDATE()),
       (CONVERT(DATETIME, '2023-06-15', 120), CONVERT(DATETIME, '2023-06-30', 120), 2, 20, GETDATE());

-- Inserção na tabela COMPRAS
INSERT INTO COMPRAS (COM_ID_CLIENTE) VALUES (1);

-- Inserção na tabela ITENS_COMPRA
INSERT INTO ITENS_COMPRA (ITEC_ID_COMPRA, ITEC_ID_PRODUTO, ITEC_QNTD, ITEC_ID_DESCONTO)
VALUES (1, 1, 2, 1),
       (1, 3, 1, NULL);

DELETE FROM ITENS_COMPRA WHERE ITEC_ID_PRODUTO = 1;
